# Generated by Django 5.2.8 on 2025-11-27 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_cita'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='duracion',
            field=models.IntegerField(blank=True, choices=[(30, '30 minutos'), (60, '1 hora')], null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='disponible_desde',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='disponible_hasta',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='duracion',
            field=models.IntegerField(choices=[(30, '30 minutos'), (60, '1 hora')], default=30),
        ),
    ]
